LOC=../../NOBUILD/bin/pbo
HFB=${LOC}/hfbsm
BOT=${LOC}/bottlefile.py
BOTMRG=${LOC}/bottlefile_merge.py

#all: hfbsm bottlefile.py bottlefile_merge.py
#
#hfbsm: $(HFB)
#	cp $(HFB) .
#
#bottlefile.py: $(BOT)
#	cp $(BOT) .
#
#bottlefile_merge.py: $(BOTMRG)
#	cp $(BOTMRG) .

TEST:
	01.test

clean:
	rm -f B084.ALL_01.[lr].txt
	rm -f prof.bottle*
	rm -f *.pyc
