all: minphs.rda clean

minphs.rda: r.minphs dec2 dec3 dec5
	rr r.minphs s

#get:
	#cp /Users/abarbour/dbase/stations/calib/*.rda .
	#
	## now part of the pborepo pkg
	#
	#
clean:
	rm -f *.Rout .RData
